databases:
  - name: lunch_bot
    databaseName: lunch_bot_production
    user: lunch_bot
    region: singapore

services:
  - type: web
    name: lunch_bot
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lunch_bot
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
